[package]
name = "termatrix"
version = "0.2.0"
authors = ["Joel Edwards <joeledwards@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.14"
cursive = "0.18.0"
rand = "0.8.5"
termion = "1.5.6"
